version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-stretch-node
        environment:
          PGHOST: localhost
          PGUSER: blog_ruby
          RAILS_ENV: test
      - image: postgres:10.14
        environment:
          POSTGRES_USER: blog_ruby
          POSTGRES_DB: blog_ruby_test
          POSTGRES_PASSWORD: "0963063105"
    executor: ruby/default
    steps:
      - checkout
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: cp .sample.env .env
      - run:
          name: Which bundler?
          command: bundle -v
      - run: bundle install --path vendor/bundle
      - run: bundle exec rails db:migrate
      - run: bundle exec rails db:seed
      - run: bundle exec rubocop
      - run: rspec
